CREATE TABLE `videos` (
	`id` text PRIMARY KEY NOT NULL,
	`rank` integer NOT NULL,
	`date` text NOT NULL,
	`title` text NOT NULL,
	`poster_text` text NOT NULL,
	`author` text NOT NULL,
	`source_url` text NOT NULL,
	`media_key` text,
	`category` text NOT NULL,
	`accent` text NOT NULL,
	`likes` integer DEFAULT 0 NOT NULL,
	`comments` integer DEFAULT 0 NOT NULL,
	`favorites` integer DEFAULT 0 NOT NULL,
	`shares` integer DEFAULT 0 NOT NULL,
	`viral_line` text NOT NULL,
	`comment_quote` text NOT NULL,
	`why_it_works` text NOT NULL,
	`insight` text NOT NULL,
	`script` text NOT NULL,
	`status` text DEFAULT '待拍' NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
